### ISSUE TITLE
Labels are not clickable

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#1]
When clicking on a label I would like to select the option.

![stickyfolios](https://user-images.githubusercontent.com/209089/31411380-0f2a0ad0-add7-11e7-8142-d28db9d61955.png)

if you put the label like this it works:

```html
  <label class="form-check-label">
    <input class="form-check-input" type="checkbox" value="">
    Option one is this and that&mdash;be sure to include why it's great
  </label>

**Comment by marcd123** [comment]
Now they are!
