### ISSUE TITLE
Credit card error message

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#11]
![mean_stack_programming_lessons](https://user-images.githubusercontent.com/209089/32178839-c3a95e5a-bd5b-11e7-9b07-3bcd13c0d461.png)

Could you create a alert.alert-danger div below the payment form for payment errors instead a alert window?

**Comment by marcd123** [comment]
![image](https://user-images.githubusercontent.com/9528376/32919247-ae5ade6a-caea-11e7-8166-6ff0eb0ccd52.png)

**Comment by marcd123** [comment]
Underway with this one. The image above demonstrates how we're listing each individual error

**Comment by marcd123** [comment]
Continued implementing this and its working great now. It will populate with errors from Square, Spreedly, and Occasion SDK. It is cleared an repopulated if need be every time there is a form submission
