### ISSUE TITLE
USe Spreedly iframe solution as specified in the SDK docs

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#13]
Currently you get the error:

> Direct API access has been disabled for this environment – payment methods can only be submitted from Spreedly Express or the iFrame payment form. If this is incorrect, the setting can be changed in your environment settings at https://id.spreedly.com.

Because you use the javascript method instead of the specified Iframe solution

**Comment by marcd123** [comment]
iFrame solution fully implemented, tested getting back card data token successfully, tested submitting order to OCCSN SDK successfully.
