### ISSUE TITLE
Replace loading image with a vector based version like jQuery spinner

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#14]
The spinner you added works great only looks like it was from the 90's :-)

Please use a vector spinner like: http://spin.js.org/

**Comment by nicklandgrebe** [comment]
Fixed in `engine` branch with this commit:

https://github.com/marcd123/StickyBooking/commit/9144d2324e31963143d048e74dc50f2d111ea934

Will be in final product
