### ISSUE TITLE
Have a fall back error message for a 401 here

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#16]
When you fill in fake API key

![loading___](https://user-images.githubusercontent.com/209089/32182366-7d95ec18-bd64-11e7-868f-fe3032255a18.png)

Currently, you get a TypeError.

**Comment by marcd123** [comment]
![image](https://user-images.githubusercontent.com/9528376/32918084-cc64e7b0-cae6-11e7-8bea-15586f12f163.png)

**Comment by marcd123** [comment]
So this one is a little tricky. I think the 401 error is received somewhere in the SDK or in active-resource where the request to your server is made. The error I get back in my catch is just the TypeError the either the SDK or active-resource spits out. 

Considering thats really the only TypeError we get in this part of the app we made the following solution. In the catch we check to see if the errors returned are an instance of TypeError. If so, we give the alert shown above. If not, the errors returned are likely a collection, so we map through them and alert each one to the user.
