### ISSUE TITLE
When having a correct API key with a wrong product ID 

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#17]
You do not see the error message:

![loading___](https://user-images.githubusercontent.com/209089/32182549-fc4d4fe2-bd64-11e7-888a-862cc006845b.png)

I think an alert is fine in this instance since it should never happen

**Comment by marcd123** [comment]
![image](https://user-images.githubusercontent.com/9528376/32915623-23c9d3ec-cadf-11e7-8e4b-2b28aba4ceef.png)

**Comment by marcd123** [comment]
Now we are mapping through the errors that come back, logging them and displaying an alert, then hiding the loading spinner.
