### ISSUE TITLE
Align checkboxes and radio buttons

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#2]
![stickyfolios](https://user-images.githubusercontent.com/209089/31411590-ad36f5c6-add7-11e7-8a9c-4892ee26fb1b.png)

**Comment by marcd123** [comment]
Are you saying you'd like less padding/margin on the left?

**Comment by kieranklaassen** [comment]
Yes I would have margin 0 on the left

**Comment by marcd123** [comment]
margin-left 0px was added
