### ISSUE TITLE
Square payments error?

### ISSUE THREAD

**Issue by marcd123** [marcd123/StickyBooking#21]
![image](https://user-images.githubusercontent.com/9528376/32930270-4704230a-cb23-11e7-8df4-758c26f4dcee.png)

Trying to test final order submission with Square but using their test card number yields this error indicating the card number is incorrect. This is using Occasion's environment key for Square.

**Comment by marcd123** [comment]
![image](https://user-images.githubusercontent.com/9528376/32930295-6b864f82-cb23-11e7-97f5-ec535c93d616.png)

Test card data from Square Docs

**Comment by kieranklaassen** [comment]
Test data only work in Test environments. I will test locally but this is not a bug per-se
