### ISSUE TITLE
Calendar load speed is very slow

### ISSUE THREAD

**Issue by aksh0925** [marcd123/StickyBooking#22]
Steps to reproduce:
1. go here - https://occ.sn/xp/ii-el1nu38vxkf-7wwe0xq
2. Click on "book now"

Expected: Calendar should load in <1 second

Actual: Calendar loads in 5 - 10 seconds

========================

Same behavior also observed when moving from November to December to January.

**Comment by kieranklaassen** [comment]
Can we try this:

1. Call the API to fetch the first 10 pages with size of 25. We have a pretty scalable server so that would be fine. 
2. Do it paralel instead of serial?

**Comment by kieranklaassen** [comment]
Third, we'll get this endpoint faster but it is a pain for us too...

**Comment by kieranklaassen** [comment]
Still not very fast to load this product:

<img width="1581" alt="schedule_your_onboarding_call" src="https://user-images.githubusercontent.com/209089/33152169-e723d6c4-cfa0-11e7-9f51-fceb05594f78.png">

Another fix would be to load 3 months in the future always. So a click on next month is almost instantaneously.

**Comment by kieranklaassen** [comment]
@pelletencate could you see why this is slow? Since we tested on another listing locally and it was fast

@nicklandgrebe what about my idea of pre loading 3 months?
