### ISSUE TITLE
Dates with no times are still showing as open

### ISSUE THREAD

**Issue by aksh0925** [marcd123/StickyBooking#23]
Steps to reproduce:
1. Go here - https://occ.sn/xp/ii-el1nu38vxkf-7wwe0xq
2. Saturday Dec 2 has not timeslots so click on that

Expected:
Customer should not be shown that as available because we don't have availability listed for Dec 2nd.

Actual:
Customer, after clicking, sees no timeslots.

**Comment by kieranklaassen** [comment]
Works on new version as far as I know
