### ISSUE TITLE
Times are not shown correctly

### ISSUE THREAD

**Issue by aksh0925** [marcd123/StickyBooking#25]
Steps to reproduce:
1. Go here - https://bookings.stickyfolios.com/xp/y8asg5if
2. Select Nov 30

Expected:
Timeslots for Nov 30 should show properly.

Actual:
Timeslots are shown in code - https://www.dropbox.com/s/nqgkfvk35p4royi/Screenshot%202017-11-17%2016.09.01.png?dl=0

**Comment by marcd123** [comment]
After merging engine branch and master, this issue has been resolved.


![image](https://user-images.githubusercontent.com/9528376/33092936-3d5450fe-cec1-11e7-9edc-91db2ef483ab.png)
