### ISSUE TITLE
Calendar does not go past December

### ISSUE THREAD

**Issue by aksh0925** [marcd123/StickyBooking#26]
Steps to reproduce:
1. Go here - https://occ.sn/xp/ii-el1nu38vxkf-7wwe0xq from your mobile browser
2. Try to go past December

Expected:
It should allow you to click and go past into January.. Feb.

Actual:
No arrow is shown after December.

Screenshot - https://secure.helpscout.net/conversation/470511616/12520?folderId=751851

**Comment by kieranklaassen** [comment]
Reproducible:

<img width="540" alt="dashboard" src="https://user-images.githubusercontent.com/209089/33095747-5ed98326-ceca-11e7-9481-6a8ec1c5c21b.png">

**Comment by marcd123** [comment]
Can't reproduce on simulated mobile screen size. I think the version on this test server is a little out of date too. Going to put the current version on a test server of ours and test on actual mobile phone. 

Does anyone experience this anywhere other than on actual mobile device?

**Comment by kieranklaassen** [comment]
<img width="630" alt="dashboard" src="https://user-images.githubusercontent.com/209089/33152303-9a5382c6-cfa1-11e7-9e92-53e54466db0b.png">


fixed
