### ISSUE TITLE
Change field labels

### ISSUE THREAD

**Issue by aksh0925** [marcd123/StickyBooking#27]
On this page - https://occ.sn/xp/ii-el1nu38vxkf-7wwe0xq

Change - YOUR E-MAIL ADDRESS* to E-MAIL ADDRESS*

Change - YOUR ZIP CODE* to BILLING ZIP/ POSTAL CODE*

**Comment by marcd123** [comment]
Just pushed a commit with this fix.


![image](https://user-images.githubusercontent.com/9528376/33156114-2a9b58c6-cfbc-11e7-8925-d80774c0fc17.png)
