### ISSUE TITLE
Price is not shown

### ISSUE THREAD

**Issue by aksh0925** [marcd123/StickyBooking#28]
Steps to reproduce:
1. Go here - https://bookings.stickyfolios.com/xp/xfsp112y
2. Scroll down to the "ADD ON FOR ADDITIONAL CD"
3. The add on is available for $14

Expected:
The price should be shown to the customer

Actual:
The price is not shown to the customer

**Comment by kieranklaassen** [comment]
For now, it looks it worked on new version
