### ISSUE TITLE
Applying coupons

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#31]
<img width="786" alt="applying coupon doesnt work" src="https://user-images.githubusercontent.com/209089/33095904-dacb38f8-ceca-11e7-91cd-99b0c5755263.png">

**Comment by kieranklaassen** [comment]
Cash Psp

**Comment by marcd123** [comment]
Tested with all three PSPs. Seems like Nick's changes fixed up the issues here before. Nick's additions to the price section are great too!

I added a loading animation for when we are validating and applying a redeemable, noticed that with a slow connection you get no feedback that its loading and it could look like nothing is happening.

Also, when we have a valid redeemable applied I disabled the input so you can't change the code in there. When you click remove, the input is re-enabled.

**Comment by kieranklaassen** [comment]
fixed
