### ISSUE TITLE
Gift card does not work

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#34]
<img width="817" alt="gift card nroken" src="https://user-images.githubusercontent.com/209089/33095982-183a90b2-cecb-11e7-9a7b-36c971b2bf3c.png">

**Comment by marcd123** [comment]
This is very interesting. This was functioning before the recent merges. Here is a video of the original functionality:

https://occasion-dev-support.slack.com/files/U78BBG150/F82DSKB1T/image_uploaded_from_ios.mov


I'll check and see if anything changed.

**Comment by kieranklaassen** [comment]
@nicklandgrebe will take a look as well.

I tested this with Cash Psp

**Comment by marcd123** [comment]
Tested with all three PSPs. Seems like Nick's changes fixed up the issues here before. Nick's additions to the price section are great too!

I added a loading animation for when we are validating and applying a redeemable, noticed that with a slow connection you get no feedback that its loading and it could look like nothing is happening.

Also, when we have a valid redeemable applied I disabled the input so you can't change the code in there. When you click remove, the input is re-enabled.

**Comment by kieranklaassen** [comment]
fixed and thanks @marcd123
