### ISSUE TITLE
Required checkbox not validating with html5

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#38]
<img width="1129" alt="required checkboxes" src="https://user-images.githubusercontent.com/209089/33096054-595bf18a-cecb-11e7-95b0-899fc1ffcea9.png">

**Comment by marcd123** [comment]
I can imagine it's due to the value in the answer.question().required. I implemented the HTML 5 required attribute binding using answer.question().required but I think a couple form controls use mustBeChecked or something of that sort instead and required returns false. Will fix

**Comment by kieranklaassen** [comment]
Well make it required and make it work. no action needed @marcd123

**Comment by kieranklaassen** [comment]
fixed
