### ISSUE TITLE
On option list with no default selected it selects the first one

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#46]
Actual:

![informational_questions_-_default_headers](https://user-images.githubusercontent.com/209089/33279673-0950d5c2-d365-11e7-8bd2-9593b908a7b0.png)

Expected:

<img width="533" alt="informational_questions_-_default_headers_png" src="https://user-images.githubusercontent.com/209089/33279678-1245c99e-d365-11e7-8f2d-960211a8ca25.png">

https://app.getoccasion.com/xp/hncuxeeynbmx4lc5xyk18g

**Comment by nicklandgrebe** [comment]
Fixed
