### ISSUE TITLE
Missing asterix* with required checkbox

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#48]
Actual:

![informational_questions_-_default_headers](https://user-images.githubusercontent.com/209089/33279837-a59305ea-d365-11e7-84a2-ea0c675676d0.png)

Expected

<img width="235" alt="informational_questions_-_default_headers_png" src="https://user-images.githubusercontent.com/209089/33279846-af314828-d365-11e7-899b-35781927374e.png">

**Comment by nicklandgrebe** [comment]
@kieranklaassen  Could not replicate, I considered this issue closed unless you can replicate it in #61

**Comment by nicklandgrebe** [comment]
Fixed
