### ISSUE TITLE
Waiver field type text can contain html

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#7]
![book_a_session](https://user-images.githubusercontent.com/209089/32076869-0730bff8-ba67-11e7-9cd0-89a69ea11c8d.png)

the waiver text contains HTML in some case so should be rendered corectly

**Comment by aaka3207** [comment]
I added an <ng-bind-html> directive to the template for rendering out the waiver information, should render innerHTML now.
