### ISSUE TITLE
Put currency symbol before currencies

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#8]
![book_a_session](https://user-images.githubusercontent.com/209089/32076912-3713a2c6-ba67-11e7-985d-d81589b4305c.png)

Could you add a currency symbol here? This should come from the SDK since we support 5 currencies. I know the merchant has a currency. Connect with @nicklandgrebe if the SDK does not make sense here

**Comment by marcd123** [comment]
added include('currency') to the initial query for merchant data, then printing merchant.curreny().code in front of subtotal, tax, and total.
